config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :bookings, only: [:index, :destroy]
  resources :yachts do
    resources :bookings
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  devise_scope :user do
    authenticated :user do
      root "yachts#index", as: :authenticated_root
    end
    unauthenticated do
      root "pages#home", as: :unauthenticated_root
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :yacht
  belongs_to :user

  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :yachts
end

app/models/yacht.rb
class Yacht < ApplicationRecord
  belongs_to :user
  has_many :bookings

  # attribute :image_url, :string
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.all
  end

  def new
    @yacht = Yacht.find(params[:yacht_id])
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @yacht = Yacht.find(params[:yacht_id])
    @booking.yacht = @yacht
    @booking.user = current_user
    @booking.total_price = (@booking.end_date - @booking.start_date) * @yacht.price_per_day
    @booking.save!
    redirect_to bookings_path, notice: 'Booking was successfully created.'
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy

    redirect_to bookings_path, notice: 'Booking has successfully destroyed.'
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :total_price)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/yachts_controller.rb
class YachtsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @yachts = Yacht.all
  end

  def show
    @yacht = Yacht.find(params[:id])
    @booking = Booking.new
  end

  def new
    @yacht = Yacht.new
  end

  def create
    @yacht = current_user.yachts.build(yacht_params)

    if @yacht.save
      redirect_to yacht_path(@yacht), notice: 'Yacht was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @yacht = Yacht.find(params[:id])
  end

  def update
    @yacht = Yacht.find(params[:id])
    @yacht.update(yacht_params)
    redirect_to yacht_path(@yacht)
  end

  def destroy
    @yacht = Yacht.find(params[:id])
    @yacht.destroy

    redirect_to yachts_path, notice: 'Yacht was successfully destroyed.'
  end

  # Add other actions as needed

  private

  def yacht_params
    params.require(:yacht).permit(:name, :price_per_day, :capacity, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="card booking-index" style="margin-bottom: 4rem;">
  <table style="width: 100%; border: 1px solid hotpink; margin-bottom: 2rem;">
    <tr>
      <th> START DATE</th>
      <th>END DATE</th>
      <th>TOTAL PRICE</th>
      <th>ACTIONS</th>
    </tr>
  <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.start_date %></td>
        <td><%= booking.end_date %></td>
        <td>$<%= booking.total_price %></td>
        <td>
          <%= link_to "Delete", booking_path(booking), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-danger" %>
        </td>
      </tr>
  <% end %>
    </table>

   <%= link_to "Back to Homepage", yachts_path, class: "btn btn-primary" %>

</div>

app/views/bookings/new.html.erb
<%= simple_form_for [@yacht, @booking] do |f| %>
  <%= f.input :start_date %>
  <%= f.input :end_date %>
  <br>
  The <%= f.label :price_per_day %> for this <%= @yacht.name %>: $<%= @yacht.price_per_day %>


  <br>
<br>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYacht</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Welcome to our Yacht Booking Page</h1>

<% if user_signed_in? %>
  <%= puts "User is signed in!" %>
  <% @yachts.each do |yacht| %>
    <div>
      <h2><%= yacht.name %></h2>
      <p><%= yacht.description %></p>
      <%= image_tag(yacht.image_url, alt: yacht.name, width: 300) %>
      <%= link_to "View Details", yacht_path(yacht) %>

      <% if current_user == yacht.user %>
        <%= link_to "Edit Yacht", edit_yacht_path(yacht) %>
        <%= link_to "Delete Yacht", yacht_path(yacht), method: :delete, data: { confirm: "Are you sure?" } %>
      <% end %>
    </div>
  <% end %>
<% else %>
  <p>No yachts available for booking.</p>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>

          <li class="nav-item">
            <%= link_to "My Bookings", bookings_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>
<!-- app/views/users/new.html.erb -->

<h1>Register</h1>

<%= form_for @user, url: users_path, method: :post do |form| %>
  <div>
    <%= form.label :first_name, 'First Name:' %>
    <%= form.text_field :first_name, required: true %>
  </div>

  <div>
    <%= form.label :last_name, 'Last Name:' %>
    <%= form.text_field :last_name, required: true %>
  </div>

  <div>
    <%= form.label :email, 'Email:' %>
    <%= form.email_field :email, required: true %>
  </div>

  <div>
    <%= form.label :password, 'Password:' %>
    <%= form.password_field :password, required: true %>
  </div>

  <div>
    <%= form.label :password_confirmation, 'Confirm Password:' %>
    <%= form.password_field :password_confirmation, required: true %>
  </div>

  <div>
    <%= form.submit 'Register' %>
  </div>
<% end %>

app/views/yachts/edit.html.erb
<!-- app/views/yachts/edit.html.erb -->

<div class="form-booking">
  <%= form_with model: @yacht do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :price_per_day %>
    <%= f.number_field :price_per_day %>

    <%= f.label :capacity %>
    <%= f.number_field :capacity %>

    <%= f.label :description %>
    <%= f.text_field :description %>

    <%= f.submit %>
  <% end %>
</div>

app/views/yachts/index.html.erb
<h1>Yachts</h1>

<% if current_user %>
  <%= link_to "New Yacht", new_yacht_path, class: "btn btn-primary" %>
<% end %>

<div class="card">
  <% @yachts.each do |yacht| %>
    <div class="card-body">
      <h2 class="card-title"><%= yacht.name %></h2>
      <p class="card-text"><%= yacht.description %></p>
      <p class="card-text">Price per Day: <%= yacht.price_per_day %></p>
      <p class="card-text">Capacity: <%= yacht.capacity %></p>

      <img src="https://www.absoluteyachts.com/web/app/uploads/2016/08/45-sty-intera.jpg" class="card-img-top" style="width: 600px;" >

      <%= link_to "View More", yacht_path(yacht), class: "btn btn-primary" %>
      <%= link_to "Edit", edit_yacht_path(yacht), class: "btn btn-secondary" %>
    </div>
  <% end %>
</div>

app/views/yachts/new.html.erb
<!-- app/views/yachts/new.html.erb -->

<div class="form-booking">
  <%= form_with model: @yacht do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :price_per_day %>
    <%= f.number_field :price_per_day %>

    <%= f.label :capacity %>
    <%= f.number_field :capacity %>

    <%= f.label :description %>
    <%= f.text_field :description %>

    <%= f.submit %>
  <% end %>
</div>

app/views/yachts/show.html.erb
<h1><%= @yacht.name %></h1>
<p><%= @yacht.description %></p>
<p>Price per Day: <%= @yacht.price_per_day %></p>
<p>Capacity: <%= @yacht.capacity %></p>

<img src="https://www.absoluteyachts.com/web/app/uploads/2016/08/45-sty-intera.jpg" style="width: 400px;">

<%= link_to "Delete", yacht_path(@yacht), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  },
                  class: "btn btn-danger"
                  %>

<%= link_to "Book this Yacht", new_yacht_booking_path(@yacht, @booking), class: "btn btn-primary" %>